[mgr]
ratio = [15, 40, 50 ]

[[mgr.prepend_keymap]]
on = [ "g", "i" ]
run = "plugin lazygit"
desc = "run lazygit"

[[plugin.prepend_previewers]]
name = "*.service"
run  = 'piper -- bat -p --color=always "$1"'

[[plugin.prepend_previewers]]
name = "*.socket"
run  = 'piper -- bat -p --color=always "$1"'

[[plugin.prepend_previewers]]
name = "*.tar*"
run = 'piper --format=url -- tar tf "$1"'

[[plugin.prepend_previewers]]
name = "*/"
run = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"'

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id  = "git"
name = "*/"
run = "git"

[[plugin.prepend_previewers]]
mime = "application/bittorrent"
run = "torrent-preview"

[[plugin.prepend_previewers]]
name = "*.md"
run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'

[[plugin.prepend_previewers]]
mime = "application/{,g}zip"
run  = "lsar"

[[plugin.prepend_previewers]]
mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}"
run  = "lsar"

[[plugin.prepend_spotters]]
name = "*"
run = "file-extra-metadata"

[tasks]
image_bound = [ 9000, 9000 ]

[preview]
cache_dir       = "~/.cache/yazi"
